<div class="container">
	<img src="http://placehold.it/300x300" class="img-reward img-rounded img-responsive">
	<h1 class="text-center">Your Reward</h1>
	<p class="text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur sapiente, incidunt enim blanditiis saepe maxime dolorem, laboriosam in id dicta exercitationem consectetur quam dignissimos vitae at quisquam error ipsa, veritatis!</p>
</div>